variables:
  GIT_SUBMODULE_STRATEGY: none

before_script:
  - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
  - which ssh-agent
  - eval $(ssh-agent -s)
  - cat "./.gitlab-ci/id_rsa" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo $(ssh-keyscan git.tsinghua.edu.cn) >> ~/.ssh/known_hosts
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - build_chisel
  - build
  - test

chisel:
  stage: build_chisel
  image: chisel
  script:
    - ./build_chisel.sh
  artifacts:
    paths:
      - thinpad_top.srcs/sources_1/new/Router.v


bitstream:
  stage: build
  image: vivado2018:2018.3
  script:
    - env
    - /opt/Xilinx/Vivado/2018.3/bin/vivado -mode tcl -source build.tcl thinpad_top.xpr

  artifacts:
    paths:
      - thinpad_top.runs/impl_1/thinpad_top.bit
      - thinpad_top.runs/impl_1/runme.log
      - thinpad_top.runs/synth_1/runme.log

